# Install Required Packages

In [1]:
# pip install fiftyone

# Import

In [8]:
import fiftyone as fo
import fiftyone.zoo as foz

In [9]:
import json

In [10]:
import pandas as pd

In [11]:
import numpy as np

# COCO Dataset Details

In [12]:
print(foz.list_zoo_datasets())

['bdd100k', 'caltech101', 'caltech256', 'cifar10', 'cifar100', 'cityscapes', 'coco-2014', 'coco-2017', 'fashion-mnist', 'hmdb51', 'imagenet-2012', 'imagenet-sample', 'kitti', 'lfw', 'mnist', 'open-images-v6', 'quickstart', 'quickstart-geo', 'quickstart-video', 'ucf101', 'voc-2007', 'voc-2012']

In [13]:
import textwrap
zoo_dataset = foz.get_zoo_dataset("coco-2017")

print("***** Dataset description *****")
print(textwrap.dedent("    " + zoo_dataset.__doc__))

print("***** Tags *****")
print("%s\n" % ", ".join(zoo_dataset.tags))

print("***** Supported splits *****")
print("%s\n" % ", ".join(zoo_dataset.supported_splits))

***** Dataset description *****
COCO is a large-scale object detection, segmentation, and captioning
dataset.

This version contains images, bounding boxes, segmentations, and keypoints
for the 2017 version of the dataset.

This dataset supports partial downloads:

-   You can specify subsets of data to download via the ``label_types``,
    ``classes``, and ``max_samples`` parameters
-   You can specify specific images to load via the ``image_ids`` parameter

See :ref:`this page <dataset-zoo-coco-2017>` for more information about
partial downloads of this dataset.

Full split stats:

-   Train split: 118,287 images
-   Test split: 40,670 images
-   Validation split: 5,000 images

Notes:

-   COCO defines 91 classes but the data only uses 80 classes
-   Some images from the train and validation sets don't have annotations
-   The test set does not have annotations
-   COCO 2014 and 2017 use the same images, but the splits are different

Example usage::

    import fiftyone as fo
    import fiftyone.zoo as foz

    #
    # Load 50 random samples from the validation split
    #
    # By default, only detections are loaded
    #

    dataset = foz.load_zoo_dataset(
        "coco-2017",
        split="validation",
        max_samples=50,
        shuffle=True,
    )

    session = fo.launch_app(dataset)

    #
    # Load segmentations for 25 samples from the validation split that
    # contain cats and dogs
    #
    # Images that contain all `classes` will be prioritized first, followed
    # by images that contain at least one of the required `classes`. If
    # there are not enough images matching `classes` in the split to meet
    # `max_samples`, only the available images will be loaded.
    #
    # Images will only be downloaded if necessary
    #

    dataset = foz.load_zoo_dataset(
        "coco-2017",
        split="validation",
        label_types=["segmentations"],
        classes=["cat", "dog"],
        max_samples=25,
    )

    session.dataset = dataset

    #
    # Download the entire validation split and load both detections and
    # segmentations
    #
    # Subsequent partial loads of the validation split will never require
    # downloading any images
    #

    dataset = foz.load_zoo_dataset(
        "coco-2017",
        split="validation",
        label_types=["detections", "segmentations"],
    )

    session.dataset = dataset

Dataset size
    25.20 GB

Source
    http://cocodataset.org/#home

Args:
    label_types (None): a label type or list of label types to load. The
        supported values are ``("detections", "segmentations")``. By
        default, only "detections" are loaded
    classes (None): a string or list of strings specifying required classes
        to load. If provided, only samples containing at least one instance
        of a specified class will be loaded
    image_ids (None): an optional list of specific image IDs to load. Can
        be provided in any of the following formats:

        -   a list of ``<image-id>`` ints or strings
        -   a list of ``<split>/<image-id>`` strings
        -   the path to a text (newline-separated), JSON, or CSV file
            containing the list of image IDs to load in either of the first
            two formats
    num_workers (None): the number of processes to use when downloading
        individual images. By default, ``multiprocessing.cpu_count()`` is
        used
    shuffle (False): whether to randomly shuffle the order in which samples
        are chosen for partial downloads
    seed (None): a random seed to use when shuffling
    max_samples (None): a maximum number of samples to load per split. If
        ``label_types`` and/or ``classes`` are also specified, first
        priority will be given to samples that contain all of the specified
        label types and/or classes, followed by samples that contain at
        least one of the specified labels types or classes. The actual
        number of samples loaded may be less than this maximum value if the
        dataset does not contain sufficient samples matching your
        requirements. By default, all matching samples are loaded

***** Tags *****
image, detection, segmentation

***** Supported splits *****
train, validation, test

# Download a Sample of DataSet

Download COCO dataset by setting the options below. If it fails then try again

In [5]:
dataset = foz.load_zoo_dataset(
    "coco-2017",
    split="train",
    label_types=["segmentation"],
    classes=["person"],
    max_samples=50,
  )

# Give the dataset a new name, and make it persistent so that you can
# work with it in future sessions
dataset.name = "coco-2017-validation-example"
dataset.persistent = True

# Visualize the in the App
session = fo.launch_app(dataset)

Downloading split 'train' to '/home/usman/fiftyone/coco-2017/train' if necessary
Found annotations at '/home/usman/fiftyone/coco-2017/raw/instances_train2017.json'
Sufficient images already downloaded
Existing download of split 'train' is sufficient
Loading existing dataset 'coco-2017-train-50'. To reload from disk, either delete the existing dataset or provide a custom `dataset_name` to use
NumExpr defaulting to 2 threads.

# Preparation for Dataset

In [8]:
with open('/home/usman/fiftyone/coco-2017/raw/person_keypoints_train2017.json', 'r') as file:
    keypoints = json.load(file)

In [9]:
keypoints.keys()

dict_keys(['info', 'licenses', 'images', 'annotations', 'categories'])

In [11]:
images_df = pd.DataFrame(keypoints['images'])
images_df

,license,file_name,coco_url,height,width,date_captured,flickr_url,id
0,3,000000391895.jpg,http://images.cocodataset.org/train2017/000000...,360,640,2013-11-14 11:18:45,http://farm9.staticflickr.com/8186/8119368305_...,391895
1,4,000000522418.jpg,http://images.cocodataset.org/train2017/000000...,480,640,2013-11-14 11:38:44,http://farm1.staticflickr.com/1/127244861_ab0c...,522418
2,3,000000184613.jpg,http://images.cocodataset.org/train2017/000000...,336,500,2013-11-14 12:36:29,http://farm3.staticflickr.com/2169/2118578392_...,184613
3,3,000000318219.jpg,http://images.cocodataset.org/train2017/000000...,640,556,2013-11-14 13:02:53,http://farm5.staticflickr.com/4125/5094763076_...,318219
4,3,000000554625.jpg,http://images.cocodataset.org/train2017/000000...,640,426,2013-11-14 16:03:19,http://farm5.staticflickr.com/4086/5094162993_...,554625
...,...,...,...,...,...,...,...,...
118282,1,000000444010.jpg,http://images.cocodataset.org/train2017/000000...,480,640,2013-11-25 14:46:11,http://farm4.staticflickr.com/3697/9303670993_...,444010
118283,3,000000565004.jpg,http://images.cocodataset.org/train2017/000000...,427,640,2013-11-25 19:59:30,http://farm2.staticflickr.com/1278/4677568591_...,565004
118284,3,000000516168.jpg,http://images.cocodataset.org/train2017/000000...,480,640,2013-11-25 21:03:34,http://farm3.staticflickr.com/2379/2293730995_...,516168
118285,4,000000547503.jpg,http://images.cocodataset.org/train2017/000000...,375,500,2013-11-25 21:20:21,http://farm1.staticflickr.com/178/423174638_1c...,547503
118286,4,000000475546.jpg,http://images.cocodataset.org/train2017/000000...,375,500,2013-11-25 21:20:23,http://farm1.staticflickr.com/167/423175046_6c...,475546

In [12]:
annotations_df = pd.DataFrame(keypoints['annotations'])
annotations_df.head()

,segmentation,num_keypoints,area,iscrowd,keypoints,image_id,bbox,category_id,id
0,"[[267.03, 243.78, 314.59, 154.05, 357.84, 136....",8,28292.08625,0,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",537548,"[267.03, 104.32, 229.19, 320]",1,183020
1,"[[640, 408.25, 639.54, 4.33, 546.25, 5.29, 426...",2,39122.63310,0,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",117891,"[206.77, 1.44, 433.23, 408.73]",1,183030
2,"[[332.57, 119.02, 327.1, 82.24, 330.75, 41.08,...",4,5634.56940,0,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",120021,"[276.12, 0.29, 61.18, 118.73]",1,183050
3,"[[364.84, 129.8, 363.74, 127.18, 363.52, 124.7...",0,672.72905,0,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",403255,"[355.87, 118.43, 30.84, 42.87]",1,183057
4,"[[187.03, 472.97, 192.43, 350.81, 181.62, 335....",13,26215.66095,0,"[0, 0, 0, 0, 0, 0, 252, 156, 2, 0, 0, 0, 248, ...",209468,"[178.38, 120.54, 114.59, 354.6]",1,183062

In [13]:
annotations_df = annotations_df[annotations_df['iscrowd'] == 0]

In [14]:
keypoints_df = pd.DataFrame(annotations_df['keypoints'].to_list(), index=annotations_df.index)

In [19]:
legs_kp_confidence_col = (np.array([11,12,15,16])*3+3)-1

In [20]:
legs_kp_confidence_col

array([35, 38, 47, 50])

In [21]:
annotations_df = annotations_df[(keypoints_df[35] > 0) & (keypoints_df[38] > 0) & (keypoints_df[47] > 0) & (keypoints_df[50] > 0)]

In [7]:
annotations_df['image_id'].unique().shape

NameError: name 'annotations_df' is not defined

In [23]:
dataset = foz.load_zoo_dataset(
    "coco-2017",
    split="train",
    label_types=["segmentation"],
    classes=["person"],
    image_ids = list(annotations_df['image_id'].unique()),
    dataset_dir='/home/usman/datasets/coco'
  )

dataset.name = "coco-2017-train-examples"
dataset.persistent = True
session = fo.launch_app(dataset)

Downloading split 'train' to '/home/usman/datasets/coco/train' if necessary
Found annotations at '/home/usman/datasets/coco/raw/instances_train2017.json'
Sufficient images already downloaded
Existing download of split 'train' is sufficient
Loading existing dataset 'coco-2017-train'. To reload from disk, either delete the existing dataset or provide a custom `dataset_name` to use